// <auto-generated />
using System;
using DBStructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DBStructure.Migrations.SlagMode
{
    [DbContext(typeof(SlagModeContext))]
    [Migration("20261010153419_FixCalcData")]
    partial class FixCalcData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DBStructure.Entities.SlagMode.BlastFurnace", b =>
                {
                    b.Property<int>("BfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BfId"));

                    b.Property<string>("BfName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BfId");

                    b.ToTable("BlastFurnaces");

                    b.HasData(
                        new
                        {
                            BfId = -1,
                            BfName = "TestBF"
                        });
                });

            modelBuilder.Entity("DBStructure.Entities.SlagMode.CalcVariant", b =>
                {
                    b.Property<int>("VariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VariantId"));

                    b.Property<int>("BfId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CalcDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("CiCContent")
                        .HasColumnType("real");

                    b.Property<float>("CiCrContent")
                        .HasColumnType("real");

                    b.Property<float>("CiMnContent")
                        .HasColumnType("real");

                    b.Property<float>("CiSContent")
                        .HasColumnType("real");

                    b.Property<float>("CiSiContent")
                        .HasColumnType("real");

                    b.Property<float>("CiTemperature")
                        .HasColumnType("real");

                    b.Property<float>("CiTiContent")
                        .HasColumnType("real");

                    b.Property<float>("CokeAshAl2O3Content")
                        .HasColumnType("real");

                    b.Property<float>("CokeAshAmount")
                        .HasColumnType("real");

                    b.Property<float>("CokeAshCaOContent")
                        .HasColumnType("real");

                    b.Property<float>("CokeAshMgOContent")
                        .HasColumnType("real");

                    b.Property<float>("CokeAshSiO2Content")
                        .HasColumnType("real");

                    b.Property<float>("CokeConsumption")
                        .HasColumnType("real");

                    b.Property<float>("CokeSContent")
                        .HasColumnType("real");

                    b.Property<bool>("IsImport")
                        .HasColumnType("boolean");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<float>("SlagAl2O3Content")
                        .HasColumnType("real");

                    b.Property<float>("SlagCaOContent")
                        .HasColumnType("real");

                    b.Property<float>("SlagMgOContent")
                        .HasColumnType("real");

                    b.Property<float>("SlagSiO2Content")
                        .HasColumnType("real");

                    b.Property<float>("SlagTiO2Content")
                        .HasColumnType("real");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VariantId");

                    b.HasIndex("BfId");

                    b.HasIndex("ParentId");

                    b.ToTable("CalcVariants");

                    b.HasData(
                        new
                        {
                            VariantId = -1,
                            BfId = -1,
                            CalcDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CiCContent = 4.702f,
                            CiCrContent = 0f,
                            CiMnContent = 0.2f,
                            CiSContent = 0.016f,
                            CiSiContent = 0.512f,
                            CiTemperature = 1450f,
                            CiTiContent = 0f,
                            CokeAshAl2O3Content = 24.6f,
                            CokeAshAmount = 12.7f,
                            CokeAshCaOContent = 7.8f,
                            CokeAshMgOContent = 2f,
                            CokeAshSiO2Content = 48.1f,
                            CokeConsumption = 419.8f,
                            CokeSContent = 0.428f,
                            IsImport = false,
                            SlagAl2O3Content = 24.6f,
                            SlagCaOContent = 40.9f,
                            SlagMgOContent = 2f,
                            SlagSiO2Content = 36.56f,
                            SlagTiO2Content = 0.01f,
                            VariantName = "-1st variant"
                        });
                });

            modelBuilder.Entity("DBStructure.Entities.SlagMode.ComponentGuide", b =>
                {
                    b.Property<int>("ComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ComponentId"));

                    b.Property<float>("Al2O3Content")
                        .HasColumnType("real");

                    b.Property<float>("CaOContent")
                        .HasColumnType("real");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("FeContent")
                        .HasColumnType("real");

                    b.Property<float>("MgOContent")
                        .HasColumnType("real");

                    b.Property<float>("MnOContent")
                        .HasColumnType("real");

                    b.Property<float>("SContent")
                        .HasColumnType("real");

                    b.Property<float>("SiO2Content")
                        .HasColumnType("real");

                    b.Property<float>("TiO2Content")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ComponentId");

                    b.ToTable("ComponentsGuide");

                    b.HasData(
                        new
                        {
                            ComponentId = -1,
                            Al2O3Content = 1.75f,
                            CaOContent = 8.72f,
                            ComponentName = "агломерат а/ф № 2 и 3",
                            FeContent = 58.5f,
                            MgOContent = 1.63f,
                            MnOContent = 0.19f,
                            SContent = 0.028f,
                            SiO2Content = 5.88f,
                            TiO2Content = 0.24f,
                            UserId = -1
                        },
                        new
                        {
                            ComponentId = -2,
                            Al2O3Content = 1.76f,
                            CaOContent = 8.86f,
                            ComponentName = "агломерат а/ф № 4",
                            FeContent = 58.3f,
                            MgOContent = 1.64f,
                            MnOContent = 0.19f,
                            SContent = 0.028f,
                            SiO2Content = 5.95f,
                            TiO2Content = 0.24f,
                            UserId = -1
                        },
                        new
                        {
                            ComponentId = -3,
                            Al2O3Content = 1.21f,
                            CaOContent = 4.02f,
                            ComponentName = "окатыши ССГПО",
                            FeContent = 62.6f,
                            MgOContent = 0.99f,
                            MnOContent = 0.16f,
                            SContent = 0.067f,
                            SiO2Content = 3.7f,
                            TiO2Content = 0.32f,
                            UserId = -1
                        },
                        new
                        {
                            ComponentId = -4,
                            Al2O3Content = 0.25f,
                            CaOContent = 0.4f,
                            ComponentName = "ЛебГОК",
                            FeContent = 65.7f,
                            MgOContent = 0.22f,
                            MnOContent = 0.05f,
                            SContent = 0.01f,
                            SiO2Content = 5.17f,
                            TiO2Content = 0f,
                            UserId = -1
                        },
                        new
                        {
                            ComponentId = -5,
                            Al2O3Content = 2.59f,
                            CaOContent = 1.28f,
                            ComponentName = "КачГОК",
                            FeContent = 60.4f,
                            MgOContent = 2.9f,
                            MnOContent = 0.23f,
                            SContent = 0.02f,
                            SiO2Content = 4.36f,
                            TiO2Content = 2.66f,
                            UserId = -1
                        },
                        new
                        {
                            ComponentId = -6,
                            Al2O3Content = 0.23f,
                            CaOContent = 1.49f,
                            ComponentName = "МихГОК",
                            FeContent = 63.3f,
                            MgOContent = 0.25f,
                            MnOContent = 0.04f,
                            SContent = 0.01f,
                            SiO2Content = 7.25f,
                            TiO2Content = 0f,
                            UserId = -1
                        },
                        new
                        {
                            ComponentId = -7,
                            Al2O3Content = 0.74f,
                            CaOContent = 0.25f,
                            ComponentName = "Сварочный шлак",
                            FeContent = 69.8f,
                            MgOContent = 0.39f,
                            MnOContent = 0.84f,
                            SContent = 0.02f,
                            SiO2Content = 4.3f,
                            TiO2Content = 0f,
                            UserId = -1
                        },
                        new
                        {
                            ComponentId = -8,
                            Al2O3Content = 2f,
                            CaOContent = 8.5f,
                            ComponentName = "Королёк",
                            FeContent = 68.4f,
                            MgOContent = 3.1f,
                            MnOContent = 0.98f,
                            SContent = 0.11f,
                            SiO2Content = 6.8f,
                            TiO2Content = 0.34f,
                            UserId = -1
                        });
                });

            modelBuilder.Entity("DBStructure.Entities.SlagMode.ComponentVariant", b =>
                {
                    b.Property<int>("VariantId")
                        .HasColumnType("integer");

                    b.Property<int>("ComponentId")
                        .HasColumnType("integer");

                    b.Property<float>("Al2O3Content")
                        .HasColumnType("real");

                    b.Property<float>("CaOContent")
                        .HasColumnType("real");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Consumption")
                        .HasColumnType("real");

                    b.Property<float>("FeContent")
                        .HasColumnType("real");

                    b.Property<float>("MgOContent")
                        .HasColumnType("real");

                    b.Property<float>("MnOContent")
                        .HasColumnType("real");

                    b.Property<float>("SContent")
                        .HasColumnType("real");

                    b.Property<float>("SiO2Content")
                        .HasColumnType("real");

                    b.Property<float>("TiO2Content")
                        .HasColumnType("real");

                    b.HasKey("VariantId", "ComponentId");

                    b.HasIndex("ComponentId");

                    b.ToTable("ComponentVariants");

                    b.HasData(
                        new
                        {
                            VariantId = -1,
                            ComponentId = -1,
                            Al2O3Content = 1.75f,
                            CaOContent = 8.72f,
                            ComponentName = "агломерат а/ф № 2 и 3",
                            Consumption = 441.5f,
                            FeContent = 58.5f,
                            MgOContent = 1.63f,
                            MnOContent = 0.19f,
                            SContent = 0.028f,
                            SiO2Content = 5.88f,
                            TiO2Content = 0.24f
                        },
                        new
                        {
                            VariantId = -1,
                            ComponentId = -2,
                            Al2O3Content = 1.76f,
                            CaOContent = 8.86f,
                            ComponentName = "агломерат а/ф № 4",
                            Consumption = 485.9f,
                            FeContent = 58.3f,
                            MgOContent = 1.64f,
                            MnOContent = 0.19f,
                            SContent = 0.028f,
                            SiO2Content = 5.95f,
                            TiO2Content = 0.24f
                        },
                        new
                        {
                            VariantId = -1,
                            ComponentId = -3,
                            Al2O3Content = 1.21f,
                            CaOContent = 4.02f,
                            ComponentName = "окатыши ССГПО",
                            Consumption = 568.7f,
                            FeContent = 62.6f,
                            MgOContent = 0.99f,
                            MnOContent = 0.16f,
                            SContent = 0.067f,
                            SiO2Content = 3.7f,
                            TiO2Content = 0.32f
                        },
                        new
                        {
                            VariantId = -1,
                            ComponentId = -4,
                            Al2O3Content = 0.25f,
                            CaOContent = 0.4f,
                            ComponentName = "ЛебГОК",
                            Consumption = 54.7f,
                            FeContent = 65.7f,
                            MgOContent = 0.22f,
                            MnOContent = 0.05f,
                            SContent = 0.01f,
                            SiO2Content = 5.17f,
                            TiO2Content = 0f
                        },
                        new
                        {
                            VariantId = -1,
                            ComponentId = -5,
                            Al2O3Content = 2.59f,
                            CaOContent = 1.28f,
                            ComponentName = "КачГОК",
                            Consumption = 54.1f,
                            FeContent = 60.4f,
                            MgOContent = 2.9f,
                            MnOContent = 0.23f,
                            SContent = 0.02f,
                            SiO2Content = 4.36f,
                            TiO2Content = 2.66f
                        },
                        new
                        {
                            VariantId = -1,
                            ComponentId = -6,
                            Al2O3Content = 0.23f,
                            CaOContent = 1.49f,
                            ComponentName = "МихГОК",
                            Consumption = 48.5f,
                            FeContent = 63.3f,
                            MgOContent = 0.25f,
                            MnOContent = 0.04f,
                            SContent = 0.01f,
                            SiO2Content = 7.25f,
                            TiO2Content = 0f
                        });
                });

            modelBuilder.Entity("DBStructure.Entities.SlagMode.CalcVariant", b =>
                {
                    b.HasOne("DBStructure.Entities.SlagMode.BlastFurnace", "BlastFurnace")
                        .WithMany("CalcVariants")
                        .HasForeignKey("BfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBStructure.Entities.SlagMode.CalcVariant", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BlastFurnace");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DBStructure.Entities.SlagMode.ComponentVariant", b =>
                {
                    b.HasOne("DBStructure.Entities.SlagMode.ComponentGuide", "ComponentGuide")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DBStructure.Entities.SlagMode.CalcVariant", "CalcVariant")
                        .WithMany("ComponentVariants")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalcVariant");

                    b.Navigation("ComponentGuide");
                });

            modelBuilder.Entity("DBStructure.Entities.SlagMode.BlastFurnace", b =>
                {
                    b.Navigation("CalcVariants");
                });

            modelBuilder.Entity("DBStructure.Entities.SlagMode.CalcVariant", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("ComponentVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
