// <auto-generated />
using System;
using DBStructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DBStructure.Migrations.SlagMode
{
    [DbContext(typeof(SlagModeContext))]
    partial class SlagModeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DBStructure.Entities.SlagMode.BlastFurnace", b =>
                {
                    b.Property<int>("BFId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BFId"));

                    b.Property<string>("BfName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BFId");

                    b.ToTable("BlastFurnaces");
                });

            modelBuilder.Entity("DBStructure.Entities.SlagMode.CalcVariant", b =>
                {
                    b.Property<int>("VariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VariantId"));

                    b.Property<int>("BFId")
                        .HasColumnType("integer");

                    b.Property<float>("CICrContent")
                        .HasColumnType("real");

                    b.Property<DateTime>("CalcDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("CiCContent")
                        .HasColumnType("real");

                    b.Property<float>("CiMnContent")
                        .HasColumnType("real");

                    b.Property<float>("CiSContent")
                        .HasColumnType("real");

                    b.Property<float>("CiSiContent")
                        .HasColumnType("real");

                    b.Property<float>("CiTemperature")
                        .HasColumnType("real");

                    b.Property<float>("CiTiContent")
                        .HasColumnType("real");

                    b.Property<float>("CokeAshAl2O3Content")
                        .HasColumnType("real");

                    b.Property<float>("CokeAshAmount")
                        .HasColumnType("real");

                    b.Property<float>("CokeAshCaOContent")
                        .HasColumnType("real");

                    b.Property<float>("CokeAshMgOContent")
                        .HasColumnType("real");

                    b.Property<float>("CokeAshSiO2Content")
                        .HasColumnType("real");

                    b.Property<float>("CokeConsumption")
                        .HasColumnType("real");

                    b.Property<float>("CokeSContent")
                        .HasColumnType("real");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<float>("SlagCaOContent")
                        .HasColumnType("real");

                    b.Property<float>("SlagSiO2Content")
                        .HasColumnType("real");

                    b.Property<float>("SlagTiO2Content")
                        .HasColumnType("real");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VariantId");

                    b.HasIndex("BFId");

                    b.HasIndex("ParentId");

                    b.ToTable("CalcVariants");
                });

            modelBuilder.Entity("DBStructure.Entities.SlagMode.ComponentGuide", b =>
                {
                    b.Property<int>("ComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ComponentId"));

                    b.Property<float>("Al2O3Content")
                        .HasColumnType("real");

                    b.Property<float>("CaOContent")
                        .HasColumnType("real");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("FeContent")
                        .HasColumnType("real");

                    b.Property<float>("MgOContent")
                        .HasColumnType("real");

                    b.Property<float>("MnOContent")
                        .HasColumnType("real");

                    b.Property<float>("SContent")
                        .HasColumnType("real");

                    b.Property<float>("SiO2Content")
                        .HasColumnType("real");

                    b.Property<float>("TiO2Content")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ComponentId");

                    b.ToTable("ComponentsGuide");
                });

            modelBuilder.Entity("DBStructure.Entities.SlagMode.ComponentVariant", b =>
                {
                    b.Property<int>("VariantId")
                        .HasColumnType("integer");

                    b.Property<int>("ComponentId")
                        .HasColumnType("integer");

                    b.Property<float>("Al2O3Content")
                        .HasColumnType("real");

                    b.Property<float>("CaOContent")
                        .HasColumnType("real");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Consumption")
                        .HasColumnType("real");

                    b.Property<float>("FeContent")
                        .HasColumnType("real");

                    b.Property<float>("MgOContent")
                        .HasColumnType("real");

                    b.Property<float>("MnOContent")
                        .HasColumnType("real");

                    b.Property<float>("SContent")
                        .HasColumnType("real");

                    b.Property<float>("SiO2Content")
                        .HasColumnType("real");

                    b.Property<float>("TiO2Content")
                        .HasColumnType("real");

                    b.HasKey("VariantId", "ComponentId");

                    b.HasIndex("ComponentId");

                    b.ToTable("ComponentVariants");
                });

            modelBuilder.Entity("DBStructure.Entities.SlagMode.CalcVariant", b =>
                {
                    b.HasOne("DBStructure.Entities.SlagMode.BlastFurnace", "BlastFurnace")
                        .WithMany("CalcVariants")
                        .HasForeignKey("BFId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBStructure.Entities.SlagMode.CalcVariant", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BlastFurnace");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DBStructure.Entities.SlagMode.ComponentVariant", b =>
                {
                    b.HasOne("DBStructure.Entities.SlagMode.ComponentGuide", "ComponentGuide")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DBStructure.Entities.SlagMode.CalcVariant", "CalcVariant")
                        .WithMany("ComponentVariants")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalcVariant");

                    b.Navigation("ComponentGuide");
                });

            modelBuilder.Entity("DBStructure.Entities.SlagMode.BlastFurnace", b =>
                {
                    b.Navigation("CalcVariants");
                });

            modelBuilder.Entity("DBStructure.Entities.SlagMode.CalcVariant", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("ComponentVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
